/**
 * Ideal angle definitions for each yoga asana.
 * Each joint has: ideal angle (degrees), tolerance (±), feedback messages, weight.
 *
 * Keypoint indices (MediaPipe Pose):
 * 0=nose, 11=left_shoulder, 12=right_shoulder,
 * 13=left_elbow, 14=right_elbow, 15=left_wrist, 16=right_wrist
 * 23=left_hip, 24=right_hip, 25=left_knee, 26=right_knee
 * 27=left_ankle, 28=right_ankle
 */

export const POSES = {
  tadasana: {
    id: 'tadasana',
    name: 'Tadasana',
    sanskrit: 'ताडासन',
    english: 'Mountain Pose',
    difficulty: 'Beginner',
    description: 'The foundation of all standing poses — align your body from head to toe.',
    benefits: ['Improves posture', 'Strengthens thighs', 'Reduces flat feet'],
    guidance: [
      'Stand with feet together',
      'Weight evenly distributed',
      'Arms at sides, palms forward',
      'Crown of head rising',
    ],
    referenceImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=500&fit=crop',
    youtubeUrl: 'https://www.youtube.com/embed/qW1MLSX0qsU',
    color: '#f97316',
    joints: [
      {
        name: 'Left Knee',
        points: [23, 25, 27], // hip-knee-ankle
        ideal: 175,
        tolerance: 10,
        weight: 1.5,
        feedbackHigh: 'Straighten your left leg — avoid bending the knee',
        feedbackLow: 'Release over-extension in your left knee',
      },
      {
        name: 'Right Knee',
        points: [24, 26, 28],
        ideal: 175,
        tolerance: 10,
        weight: 1.5,
        feedbackHigh: 'Straighten your right leg — avoid bending the knee',
        feedbackLow: 'Release over-extension in your right knee',
      },
      {
        name: 'Left Elbow',
        points: [11, 13, 15],
        ideal: 170,
        tolerance: 15,
        weight: 1.0,
        feedbackHigh: 'Extend your left arm fully alongside your body',
        feedbackLow: 'Relax your left arm — avoid tensing the elbow',
      },
      {
        name: 'Right Elbow',
        points: [12, 14, 16],
        ideal: 170,
        tolerance: 15,
        weight: 1.0,
        feedbackHigh: 'Extend your right arm fully alongside your body',
        feedbackLow: 'Relax your right arm — avoid tensing the elbow',
      },
      {
        name: 'Left Hip',
        points: [11, 23, 25],
        ideal: 175,
        tolerance: 10,
        weight: 2.0,
        feedbackHigh: 'Stand tall — avoid bending at the hip',
        feedbackLow: 'Do not lean backward — keep hips neutral',
      },
      {
        name: 'Right Hip',
        points: [12, 24, 26],
        ideal: 175,
        tolerance: 10,
        weight: 2.0,
        feedbackHigh: 'Stand tall — avoid bending at the hip',
        feedbackLow: 'Do not lean backward — keep hips neutral',
      },
    ],
  },

  trikonasana: {
    id: 'trikonasana',
    name: 'Trikonasana',
    sanskrit: 'त्रिकोणासन',
    english: 'Triangle Pose',
    difficulty: 'Beginner',
    description: 'Open your hips and chest while lengthening the sides of your torso.',
    benefits: ['Stretches hips & thighs', 'Opens chest', 'Improves balance'],
    guidance: [
      'Feet 3-4 feet apart',
      'Right foot out 90°, left foot in 15°',
      'Extend arms parallel to floor',
      'Reach right hand to shin/ankle',
      'Left arm points to sky',
    ],
    referenceImage: 'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=400&h=500&fit=crop',
    youtubeUrl: 'https://www.youtube.com/embed/X-EIlBkiazA',
    color: '#6d28d9',
    joints: [
      {
        name: 'Front Knee',
        points: [24, 26, 28],
        ideal: 175,
        tolerance: 10,
        weight: 2.0,
        feedbackHigh: 'Keep your front leg straight — do not bend the knee',
        feedbackLow: 'Ease up on locking the front knee',
      },
      {
        name: 'Back Knee',
        points: [23, 25, 27],
        ideal: 175,
        tolerance: 10,
        weight: 2.0,
        feedbackHigh: 'Straighten your back leg fully',
        feedbackLow: 'Relax the back leg — do not over-extend',
      },
      {
        name: 'Right Elbow',
        points: [12, 14, 16],
        ideal: 170,
        tolerance: 15,
        weight: 1.0,
        feedbackHigh: 'Keep your upper arm straight — extend to the sky',
        feedbackLow: 'Relax the upper arm',
      },
      {
        name: 'Left Elbow',
        points: [11, 13, 15],
        ideal: 160,
        tolerance: 15,
        weight: 1.0,
        feedbackHigh: 'Straighten the lower arm toward your shin',
        feedbackLow: 'Do not press too hard into the lower arm',
      },
      {
        name: 'Hip Tilt',
        points: [11, 23, 24],
        ideal: 100,
        tolerance: 15,
        weight: 2.5,
        feedbackHigh: 'Tilt from your hip — do not crunch the side',
        feedbackLow: 'Open your hips more — rotate them outward',
      },
    ],
  },

  vrikshasana: {
    id: 'vrikshasana',
    name: 'Vrikshasana',
    sanskrit: 'वृक्षासन',
    english: 'Tree Pose',
    difficulty: 'Beginner',
    description: 'Balance on one leg like a rooted tree — steady mind, steady body.',
    benefits: ['Improves balance', 'Strengthens ankles', 'Calms the mind'],
    guidance: [
      'Stand on left leg firmly',
      'Place right foot on inner thigh',
      'Join palms at chest (Namaste)',
      'Raise arms overhead',
      'Focus gaze on one point',
    ],
    referenceImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=500&fit=crop',
    youtubeUrl: 'https://www.youtube.com/embed/tVWp1Fk7s0A',
    color: '#0d9488',
    joints: [
      {
        name: 'Standing Knee',
        points: [23, 25, 27],
        ideal: 175,
        tolerance: 10,
        weight: 2.5,
        feedbackHigh: 'Keep your standing leg straight and strong',
        feedbackLow: 'Micro-bend the standing knee — do not lock it',
      },
      {
        name: 'Hip Alignment',
        points: [11, 23, 25],
        ideal: 178,
        tolerance: 8,
        weight: 2.0,
        feedbackHigh: 'Open your hip — square your hips forward',
        feedbackLow: 'Do not lean — keep hips level',
      },
      {
        name: 'Left Shoulder',
        points: [13, 11, 23],
        ideal: 160,
        tolerance: 20,
        weight: 1.5,
        feedbackHigh: 'Raise your arms higher — palms together overhead',
        feedbackLow: 'Relax the shoulders — do not shrug',
      },
      {
        name: 'Right Shoulder',
        points: [14, 12, 24],
        ideal: 160,
        tolerance: 20,
        weight: 1.5,
        feedbackHigh: 'Raise your arms higher — reach to the sky',
        feedbackLow: 'Relax the shoulders — do not shrug',
      },
    ],
  },

  warrior1: {
    id: 'warrior1',
    name: 'Virabhadrasana I',
    sanskrit: 'वीरभद्रासन १',
    english: 'Warrior I',
    difficulty: 'Intermediate',
    description: 'Channel the spirit of the warrior — strength, focus, and grace.',
    benefits: ['Strengthens legs', 'Opens chest', 'Builds stamina'],
    guidance: [
      'Step right foot forward 4 feet',
      'Back heel at 45°',
      'Bend right knee over ankle',
      'Raise arms overhead',
      'Look up between hands',
    ],
    referenceImage: 'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=400&h=500&fit=crop',
    youtubeUrl: 'https://www.youtube.com/embed/LJcKxJKXMxg',
    color: '#e11d48',
    joints: [
      {
        name: 'Front Knee',
        points: [24, 26, 28],
        ideal: 90,
        tolerance: 15,
        weight: 2.5,
        feedbackHigh: 'Bend your front knee deeper — aim for 90°',
        feedbackLow: 'Bend the front knee less — keep it over the ankle',
      },
      {
        name: 'Back Knee',
        points: [23, 25, 27],
        ideal: 170,
        tolerance: 15,
        weight: 2.0,
        feedbackHigh: 'Straighten your back leg — press the heel down',
        feedbackLow: 'Do not over-extend the back leg',
      },
      {
        name: 'Left Arm',
        points: [13, 11, 23],
        ideal: 160,
        tolerance: 20,
        weight: 1.5,
        feedbackHigh: 'Raise your arms high — reach for the sky',
        feedbackLow: 'Relax arms — avoid tensing shoulders',
      },
      {
        name: 'Spine',
        points: [11, 23, 25],
        ideal: 150,
        tolerance: 15,
        weight: 2.0,
        feedbackHigh: 'Open your chest — lift your torso tall',
        feedbackLow: 'Do not lean back excessively',
      },
    ],
  },

  warrior2: {
    id: 'warrior2',
    name: 'Virabhadrasana II',
    sanskrit: 'वीरभद्रासन २',
    english: 'Warrior II',
    difficulty: 'Intermediate',
    description: 'Expand your presence — arms wide, gaze fierce, stance powerful.',
    benefits: ['Strengthens legs & arms', 'Opens hips', 'Improves focus'],
    guidance: [
      'Feet 4-5 feet apart',
      'Right foot out 90°, left foot in slightly',
      'Bend right knee over ankle',
      'Arms parallel to floor',
      'Gaze over right fingertips',
    ],
    referenceImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=500&fit=crop',
    youtubeUrl: 'https://www.youtube.com/embed/2S33F4kQrhs',
    color: '#d97706',
    joints: [
      {
        name: 'Front Knee',
        points: [24, 26, 28],
        ideal: 90,
        tolerance: 15,
        weight: 2.5,
        feedbackHigh: 'Bend your front knee to 90° — align with ankle',
        feedbackLow: 'Straighten the front knee slightly',
      },
      {
        name: 'Back Knee',
        points: [23, 25, 27],
        ideal: 175,
        tolerance: 10,
        weight: 2.0,
        feedbackHigh: 'Keep your back leg straight and strong',
        feedbackLow: 'Ease up on the back leg',
      },
      {
        name: 'Left Elbow',
        points: [11, 13, 15],
        ideal: 170,
        tolerance: 15,
        weight: 1.5,
        feedbackHigh: 'Extend your left arm fully — reach out to the left',
        feedbackLow: 'Relax your elbow',
      },
      {
        name: 'Right Elbow',
        points: [12, 14, 16],
        ideal: 170,
        tolerance: 15,
        weight: 1.5,
        feedbackHigh: 'Extend your right arm fully — reach to the right',
        feedbackLow: 'Relax your elbow',
      },
      {
        name: 'Hip Open',
        points: [11, 23, 24],
        ideal: 155,
        tolerance: 15,
        weight: 2.0,
        feedbackHigh: 'Open your hips wider — rotate outward',
        feedbackLow: 'Bring hips slightly more forward',
      },
    ],
  },

  downwarddog: {
    id: 'downwarddog',
    name: 'Adho Mukha Svanasana',
    sanskrit: 'अधोमुखश्वानासन',
    english: 'Downward Dog',
    difficulty: 'Beginner',
    description: 'Inverted V-shape — a full body stretch and energizing reset.',
    benefits: ['Stretches hamstrings', 'Strengthens arms', 'Calms the brain'],
    guidance: [
      'Start on hands and knees',
      'Push hips up and back',
      'Straighten arms and legs',
      'Press heels toward floor',
      'Head between arms',
    ],
    referenceImage: 'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=400&h=500&fit=crop',
    youtubeUrl: 'https://www.youtube.com/embed/FjMxaqKxjBg',
    color: '#0891b2',
    joints: [
      {
        name: 'Left Arm',
        points: [11, 13, 15],
        ideal: 165,
        tolerance: 15,
        weight: 2.0,
        feedbackHigh: 'Straighten your arms fully — push the floor away',
        feedbackLow: 'Ease the arm extension',
      },
      {
        name: 'Right Arm',
        points: [12, 14, 16],
        ideal: 165,
        tolerance: 15,
        weight: 2.0,
        feedbackHigh: 'Straighten your arms fully — push the floor away',
        feedbackLow: 'Ease the arm extension',
      },
      {
        name: 'Left Knee',
        points: [23, 25, 27],
        ideal: 170,
        tolerance: 15,
        weight: 2.0,
        feedbackHigh: 'Straighten your left leg — press heel down',
        feedbackLow: 'Micro-bend if hamstrings are tight',
      },
      {
        name: 'Right Knee',
        points: [24, 26, 28],
        ideal: 170,
        tolerance: 15,
        weight: 2.0,
        feedbackHigh: 'Straighten your right leg — press heel down',
        feedbackLow: 'Micro-bend if hamstrings are tight',
      },
      {
        name: 'Hip Angle',
        points: [11, 23, 25],
        ideal: 60,
        tolerance: 15,
        weight: 3.0,
        feedbackHigh: 'Push hips higher — create a sharp V shape',
        feedbackLow: 'Lower your hips slightly',
      },
    ],
  },

  bhujangasana: {
    id: 'bhujangasana',
    name: 'Bhujangasana',
    sanskrit: 'भुजङ्गासन',
    english: 'Cobra Pose',
    difficulty: 'Beginner',
    description: 'Rise like a cobra — open the chest and strengthen the spine.',
    benefits: ['Opens chest', 'Strengthens spine', 'Reduces back pain'],
    guidance: [
      'Lie face down',
      'Place palms under shoulders',
      'Press up, straightening arms',
      'Roll shoulders back and down',
      'Keep hips on floor',
    ],
    referenceImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=500&fit=crop',
    youtubeUrl: 'https://www.youtube.com/embed/s-16lMoHvMM',
    color: '#7c3aed',
    joints: [
      {
        name: 'Left Elbow',
        points: [11, 13, 15],
        ideal: 140,
        tolerance: 20,
        weight: 2.0,
        feedbackHigh: 'Straighten arms more — lift chest higher',
        feedbackLow: 'Keep a slight bend in elbows — protect lower back',
      },
      {
        name: 'Right Elbow',
        points: [12, 14, 16],
        ideal: 140,
        tolerance: 20,
        weight: 2.0,
        feedbackHigh: 'Straighten arms more — lift chest higher',
        feedbackLow: 'Keep a slight bend in elbows',
      },
      {
        name: 'Spine Curve',
        points: [11, 23, 25],
        ideal: 130,
        tolerance: 20,
        weight: 3.0,
        feedbackHigh: 'Arch your back more — lift your chest to the sky',
        feedbackLow: 'Do not over-arch — protect your lower back',
      },
    ],
  },

  balasana: {
    id: 'balasana',
    name: 'Balasana',
    sanskrit: 'बालासन',
    english: "Child's Pose",
    difficulty: 'Beginner',
    description: 'A restful pose of surrender — perfect for rest and reflection.',
    benefits: ['Releases tension', 'Stretches hips', 'Calms the mind'],
    guidance: [
      'Kneel, toes together',
      'Sit back on heels',
      'Fold forward, arms extended',
      'Forehead rests on mat',
      'Breathe deeply',
    ],
    referenceImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=500&fit=crop',
    youtubeUrl: 'https://www.youtube.com/embed/qKXLlzuVWFc',
    color: '#059669',
    joints: [
      {
        name: 'Left Knee Fold',
        points: [23, 25, 27],
        ideal: 40,
        tolerance: 20,
        weight: 2.5,
        feedbackHigh: 'Fold deeper — sit your hips toward your heels',
        feedbackLow: 'Ease up if knees or ankles are uncomfortable',
      },
      {
        name: 'Right Knee Fold',
        points: [24, 26, 28],
        ideal: 40,
        tolerance: 20,
        weight: 2.5,
        feedbackHigh: 'Fold deeper — sit your hips toward your heels',
        feedbackLow: 'Ease up if knees or ankles are uncomfortable',
      },
      {
        name: 'Arms Extended',
        points: [11, 13, 15],
        ideal: 170,
        tolerance: 20,
        weight: 1.5,
        feedbackHigh: 'Reach your arms forward — stretch through fingertips',
        feedbackLow: 'Relax the arms — do not strain',
      },
    ],
  },
};

export const POSE_LIST = Object.values(POSES);
